# " and # not ffound because bug founding
def encode(text):
    text = text.replace("A", "#0#" )
    text = text.replace("a", "#1#" )
    text = text.replace("B", "#2#" )
    text = text.replace("b", "#3#" )
    text = text.replace("C", "#4#" )
    text = text.replace("c", "#5#" )
    text = text.replace("D", "#6#" )
    text = text.replace("d", "#7#" )
    text = text.replace("E", "#8#" )
    text = text.replace("e", "#9#" )
    text = text.replace("F", "#10#" )
    text = text.replace("f", "#11#" )
    text = text.replace("G", "#12#" )
    text = text.replace("g", "#13#" )
    text = text.replace("H", "#14#" )
    text = text.replace("h", "#15#" )
    text = text.replace("I", "#16#" )
    text = text.replace("i", "#17#" )
    text = text.replace("J", "#18#" )
    text = text.replace("j", "#19#" )
    text = text.replace("K", "#20#" )
    text = text.replace("k", "#21#" )
    text = text.replace("L", "#22#" )
    text = text.replace("l", "#23#" )
    text = text.replace("M", "#24#" )
    text = text.replace("m", "#25#" )
    text = text.replace("N", "#26#" )
    text = text.replace("n", "#27#" )
    text = text.replace("O", "#28#" )
    text = text.replace("o", "#29#" )
    text = text.replace("P", "#30#" )
    text = text.replace("p", "#31#" )
    text = text.replace("Q", "#32#" )
    text = text.replace("q", "#33#" )
    text = text.replace("R", "#34#" )
    text = text.replace("r", "#35#" )
    text = text.replace("S", "#36#" )
    text = text.replace("s", "#37#" )
    text = text.replace("T", "#38#" )
    text = text.replace("t", "#39#" )
    text = text.replace("U", "#40#" )
    text = text.replace("u", "#41#" )
    text = text.replace("V", "#42#" )
    text = text.replace("v", "#43#" )
    text = text.replace("W", "#44#" )
    text = text.replace("w", "#45#" )
    text = text.replace("X", "#46#" )
    text = text.replace("x", "#47#" )
    text = text.replace("Y", "#48#" )
    text = text.replace("y", "#49#" )
    text = text.replace("Z", "#50#" )
    text = text.replace("z", "#51#" )
    """
    text = text.replace("0", "#52#" )
    text = text.replace("1", "#53#" )
    text = text.replace("2", "#54#" )
    text = text.replace("3", "#55#" )
    text = text.replace("4", "#56#" )
    text = text.replace("5", "#57#" )
    text = text.replace("6", "#58#" )
    text = text.replace("7", "#59#" )
    text = text.replace("8", "#60#" )
    text = text.replace("9", "#61#" )
    """
    text = text.replace("=", "#62#" )
    text = text.replace("!", "#63#" )
    text = text.replace("?", "#64#" )
    text = text.replace("-", "#65#" )
    text = text.replace("_", "#66#" )
    text = text.replace(".", "#67#" )
    text = text.replace(":", "#68#" )
    text = text.replace(",", "#69#" )
    text = text.replace("(", "#70#" )
    text = text.replace(")", "#71#" )
    #text = text.replace("[", "#72#" ) sorunlu
    #text = text.replace("]", "#73#" ) sorunlu
    text = text.replace("{", "#74#" )
    text = text.replace("}", "#75#" )
    text = text.replace("+", "#76#" )
    text = text.replace("'", "#77#" )
    text = text.replace("/", "#78#" )
    text = text.replace("%", "#79#" )
    text = text.replace("&", "#80#" )
    text = text.replace("|", "#82#" )
    text = text.replace("$", "#83#" )
    text = text.replace("~", "#84#" )
    text = text.replace(";", "#85#" )
    text = text.replace("^", "#86#" )
    text = text.replace("@", "#87#" )
    text = text.replace("é", "#88#" )
    text = text.replace("<", "#89#" )
    text = text.replace(">", "#90#" )
    return text
print(encode("hello"))
def decode(tedo):
    tedo = tedo.replace('#0#', "A" )
    tedo = tedo.replace('#1#', "a" )
    tedo = tedo.replace('#2#', "B" )
    tedo = tedo.replace('#3#', "b" )
    tedo = tedo.replace('#4#', "C" )
    tedo = tedo.replace('#5#', "c" )
    tedo = tedo.replace('#6#', "D" )
    tedo = tedo.replace('#7#', "d" )
    tedo = tedo.replace('#8#', "E" )
    tedo = tedo.replace('#9#', "e" )
    tedo = tedo.replace('#10#', "F" )
    tedo = tedo.replace('#11#', "f" )
    tedo = tedo.replace('#12#', "G" )
    tedo = tedo.replace('#13#', "g" )
    tedo = tedo.replace('#14#', "H" )
    tedo = tedo.replace('#15#', "h" )
    tedo = tedo.replace('#16#', "I" )
    tedo = tedo.replace('#17#', "i" )
    tedo = tedo.replace('#18#', "J" )
    tedo = tedo.replace('#19#', "j" )
    tedo = tedo.replace('#20#', "K" )
    tedo = tedo.replace('#21#', "k" )
    tedo = tedo.replace('#22#', "L" )
    tedo = tedo.replace('#23#', "l" )
    tedo = tedo.replace('#24#', "M" )
    tedo = tedo.replace('#25#', "m" )
    tedo = tedo.replace('#26#', "N" )
    tedo = tedo.replace('#27#', "n" )
    tedo = tedo.replace('#28#', "O" )
    tedo = tedo.replace('#29#', "o" )
    tedo = tedo.replace('#30#', "P" )
    tedo = tedo.replace('#31#', "p" )
    tedo = tedo.replace('#32#', "Q" )
    tedo = tedo.replace('#33#', "q" )
    tedo = tedo.replace('#34#', "R" )
    tedo = tedo.replace('#35#', "r" )
    tedo = tedo.replace('#36#', "S" )
    tedo = tedo.replace('#37#', "s" )
    tedo = tedo.replace('#38#', "T" )
    tedo = tedo.replace('#39#', "t" )
    tedo = tedo.replace('#40#', "U" )
    tedo = tedo.replace('#41#', "u" )
    tedo = tedo.replace('#42#', "V" )
    tedo = tedo.replace('#43#', "v" )
    tedo = tedo.replace('#44#', "W" )
    tedo = tedo.replace('#45#', "w" )
    tedo = tedo.replace('#46#', "X" )
    tedo = tedo.replace('#47#', "x" )
    tedo = tedo.replace('#48#', "Y" )
    tedo = tedo.replace('#49#', "y" )
    tedo = tedo.replace('#50#', "Z" )
    tedo = tedo.replace('#51#', "z" )

    tedo = tedo.replace('~ ~', "0" )
    """
    tedo = tedo.replace('#53#', "1" )
    tedo = tedo.replace('#54#', "2" )
    tedo = tedo.replace('#55#', "3" )
    tedo = tedo.replace('#56#', "4" )
    tedo = tedo.replace('#57#', "5" )
    tedo = tedo.replace('#58#', "6" )
    tedo = tedo.replace('#59#', "7" )
    tedo = tedo.replace('#60#', "8" )
    tedo = tedo.replace('#61#', "9" )
    """

    tedo = tedo.replace('#62#', "=" )
    tedo = tedo.replace('#63#', "!" )
    tedo = tedo.replace('#64#', "?" )
    tedo = tedo.replace('#65#', "-" )
    tedo = tedo.replace('#66#', "_" )
    tedo = tedo.replace('#67#', "." )
    tedo = tedo.replace('#68#', ":" )
    tedo = tedo.replace('#69#', "," )
    tedo = tedo.replace('#70#', "(" )
    tedo = tedo.replace('#71#', ")" )
    #tedo = tedo.replace('#72#', "[" ) sorunlu
    #tedo = tedo.replace('#73#', "]" ) sorunlu
    tedo = tedo.replace('#74#', "{" )
    tedo = tedo.replace('#75#', "}" )
    tedo = tedo.replace('#76#', "+" )
    tedo = tedo.replace('#77#', "'" )
    tedo = tedo.replace('#78#', "/" )
    tedo = tedo.replace('#79#', "%" )
    tedo = tedo.replace('#80#', "&" )
    tedo = tedo.replace('#82#', "|" )
    tedo = tedo.replace('#83#', "$" )
    tedo = tedo.replace('#84#', "~" )# sayıılar için ~ ve boşluk kullan
    tedo = tedo.replace('#85#', ";" )
    tedo = tedo.replace('#86#', "^" )
    tedo = tedo.replace('#87#', "@" )
    tedo = tedo.replace('#88#', "é" )
    tedo = tedo.replace('#89#', "<" )
    tedo = tedo.replace('#90#', ">" )
    return tedo
exec(decode(encode("print('hello')")))# garip bir payload
def test():
    with open("lhost_4444_payload.txt", "r") as F:
        entero = encode(F.read())
        F.close()
    with open("de_payload.txt", "w") as f:
        f.write(entero)
        f.close()
    print("bitti")
    with open("de_payload.txt","r") as fi:
        entor = decode(fi.read())
    with open("payload.txt","w") as fir:
        fir.write(entor)
